<h2><i class="fas fa-utensils"> Réservation d'une table </i></h2>
<form class="generic-form" method="post" action="<?= $requestUrl ?>/booking">
   <fieldset>
        <legend>Informations</legend>
    <ul>
    <li>
        <label>Date de réservation :</label>
        
            <select id="day" name="day">
             <?php for($i=01;$i<=31;$i++): ?>
             <option value="<?=$i?>"><?=$i?></option>
            <?php endfor; ?>
        </select> 
        <span>/</span>
        <select id="month" name="month">
              <option selected>01</option>
              <option>02</option>
              <option>03</option>
              <option>04</option>
              <option>05</option>
              <option>06</option>
              <option>07</option>
              <option>08</option>
              <option>09</option>
              <option>10</option>
              <option>11</option>
              <option>12</option>
        </select>
         <span>/</span>
        
        <select id="year" name="year">
            <?php for($i=date('Y');$i<=date('Y')+10;$i++): ?>
            <option value="<?=$i?>"><?=$i?></option>
            <?php endfor; ?>
        </select>
       <p class="booking">à</p>
       <select name="hour">
             <?php for($i=00;$i<=23;$i++): ?>
             <option value="<?=$i?>"><?=$i?></option>
            <?php endfor; ?>
        </select> 
        <span>:</span>
        <select  name="minutes">
             <?php for($i=00;$i<=59;$i++): ?>
             <option value="<?=$i?>"><?=$i?></option>
            <?php endfor; ?>
        </select> 
    </li>
    <li> 
        <label >Nombre de couverts</label>
        <select name="couvert">
             <?php for($i=01;$i<=31;$i++): ?>
             <option value="<?=$i?>"><?=$i?></option>
            <?php endfor; ?>
        </select> 
    </li>
    </ul>
    </fieldset>
    <button class="button button-primary" type="submit">Réserver</button>
    <button class="button button-cancel" type="reset"> Annuler</button>
</form>